import logging
from typing import List
import numpy as np
from sentence_transformers import SentenceTransformer

logger = logging.getLogger("codeatlas.ai.embeddings")


class LocalEmbeddingModel:
    """
    Cached singleton for generating embeddings locally using a SentenceTransformer model.
    """

    _instance = None

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(LocalEmbeddingModel, cls).__new__(cls)
            cls._instance._initialized = False
        return cls._instance

    def __init__(self, model_name: str = "BAAI/bge-small-en-v1.5"):
        """
        Initializes the embedding model if not already initialized.
        """
        if self._initialized:
            return

        logger.info(f"Loading local embedding model: {model_name}...")
        try:
            self.model = SentenceTransformer(model_name)
            logger.info("Local embedding model loaded successfully.")
        except Exception as e:
            logger.error(f"Failed to load embedding model '{model_name}': {e}")
            logger.info("Falling back to default 'all-MiniLM-L6-v2' model...")
            self.model = SentenceTransformer("all-MiniLM-L6-v2")
            logger.info("Fallback embedding model loaded successfully.")

        self._initialized = True

    def get_embedding(self, text: str) -> np.ndarray:
        """
        Generates a normalized embedding for a single text input.

        Args:
            text (str): The input string to embed.

        Returns:
            np.ndarray: The L2-normalized embedding vector.
        """
        # normalize_embeddings=True ensures cosine similarity is equivalent to Inner Product
        embeddings = self.model.encode([text], normalize_embeddings=True)
        return np.asarray(embeddings)[0]

    def get_embeddings(self, texts: List[str]) -> np.ndarray:
        """
        Generates normalized embeddings for a list of text inputs.

        Args:
            texts (List[str]): List of input strings.

        Returns:
            np.ndarray: A 2D numpy array of shape (num_texts, embedding_dimension).
        """
        if not texts:
            return np.empty((0, self.get_dimension()), dtype=np.float32)
        embeddings = self.model.encode(texts, normalize_embeddings=True)
        return np.asarray(embeddings)

    def get_dimension(self) -> int:
        """
        Returns the dimension of the embedding vectors generated by this model.
        """
        dim = self.model.get_embedding_dimension()
        if dim is None:
            return 384  # Default fallback dimension for BAAI/bge-small-en-v1.5 and all-MiniLM-L6-v2
        return dim


# Global helper instance
_model_instance = None


def get_embedding_model() -> LocalEmbeddingModel:
    """
    Returns the singleton instance of the LocalEmbeddingModel.
    """
    global _model_instance
    if _model_instance is None:
        _model_instance = LocalEmbeddingModel()
    return _model_instance
